- name: Create bind.sh
  copy:
    src: ../files/bind.sh
    dest: /tmp/

- name: Make bind script executable
  file:
    dest: /tmp/bind.sh
    mode: u+x

- name: Execute bind script
  shell: bash /tmp/bind.sh "{{ provision_params.THREESCALE_ACCESS_TOKEN }}" "https://{{ provision_params.THREESCALE_DOMAIN }}" "{{ provision_params.THREESCALE_SERVICE_ID }}" "{{ bind_params.apicast_route }}" "{{ bind_params.service_route }}" "{{ bind_params.service_name }}" "{{ bind_params.app_key }}"

- name: Get 3Scale App ID
  shell: bash /tmp/app_id.sh "{{ provision_params.THREESCALE_ACCESS_TOKEN }}" "https://{{ provision_params.THREESCALE_DOMAIN }}" "{{ provision_params.THREESCALE_SERVICE_ID }}"
  register: threescale_app_id

- debug: var=threescale_app_id.stdout

- name: Create 3scale secret
  template:
    src: bind.json.j2
    dest: /tmp/bind-raw.json

- name: check file contents
  shell: cat /tmp/bind-raw.json
  register: bind_raw

- debug: var=bind_raw.stdout

- name: Encode bind details
  shell: "cat /tmp/bind-raw.json | base64 -w 0 > /var/tmp/bind-creds"