- name: "Create 3scale basic-auth secret template"
  template:
    src: secret.yml.j2
    dest: /tmp/secret.yaml

- name: "Create 3scale basic-auth secret"
  shell: "oc create -f /tmp/secret.yaml"

- name: "Create 3scale resources"
  shell: "oc new-app -f {{ threescale_deploy_template }}"

- name: "Update deployment image name"
  shell: "oc patch dc/apicast --type='json' -p='[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\":\"{{ threescale_image }}\"}]'"

- name: "Expose route for 3scale"
  shell: "oc expose service apicast --port={{ threescale_port }}"

