- 
  name: delete 3scale redis resources
  command: oc delete {{ item }} {{ threescale_redis_name }}
  with_items:
    - service
    - dc
- 
  name: delete apicast resoures
  command: oc delete {{ item }} {{ threescale_name }}
  with_items:
    - secret
    - dc
    - service
    - route